Vagrant.configure("2") do |config|
  # config.vm.box = "k8s-control-plane"  # Use the box name that you just added

  (1..2).each do |i|
    config.vm.define "control-plane-#{i}" do |node|
      node.vm.box = "k8s-control-plane"
      node.vm.hostname = "control-plane-#{i}"

      node.vm.network "private_network", ip: "192.168.56.#{i+1}"

      node.ssh.username = "packer"
      node.ssh.private_key_path = "~/.ssh/id_rsa"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "control-plane-#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end
end

